apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:6V2qS0zkd74=,iv:m3qadBoCDNAo+kC0zzivHKjNYkyrIVW0NBGyoluxg70=,tag:wcp/X+8ubGF3+rts34ugKQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:zLCI//ecZX7Km9d/UjqUAw==,iv:0y+rnirlV6ga78L7P1pG/ufmXQFHoJ9Cm4ro4UKyUTs=,tag:XcpoQ2bm/E8XyqJlPquOxw==,type:str]
kind: Secret
metadata:
    name: user-secret
    namespace: linkding
sops:
    age:
        - recipient: age18s5gy33a29p073jnzw92crk25fa0pfqh8ayhm3d8nmrv2pz97yyq5mgaem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVkZYMDhOaFZ5QVdxUDk2
            bEFzTEU1UkFNdHlJTHhUZFcvZXJWMFo1WENFCitCRlhMQ3lmazY4K2lZYnRnK2to
            L0pJS1F4Q2dESXNrODFML2hhbHo2ZFkKLS0tIGZDWWgweFJUUThDY3V1L1c2YU9h
            cXJzUFUrWDhnZ2tSelNPOXBzQ0F0WlUKrQpOqv5D/BEufdLgoyup2f7Cg6OWJw5J
            RiP9IIN5OcL6w5LmKexDoBOaK0EsRMzBCFUAfz/OyyTy7n7U6CgxmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T12:36:18Z"
    mac: ENC[AES256_GCM,data:y0rgn2ur8Dav2p+wWsTTagOGDr///PeX2L/hY+2kCY8vbA/PjxFvelzTofQ5EwLpg7PM6X3ckJNN7Sv4/6bMxaNcAT0JAJQH2WS1rfIbqnBHD6hpmX2DOCfkxoFS2IWkX2MqdstmKS0gzHNyXXVsBnO0kFaA2qb0NTqabMz/VnM=,iv:RhXoAyJsp/SvBTgCzwrZTg9fWu2lctzgugusBSTB2LQ=,tag:oMk2kIu3BBR2l2KngB9teA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
