apiVersion: v2
name: clickstack
version: 0.0.0
dependencies:
  # - name: clickstack-operators
  #   version: "1.0.0"
  #   repository: https://clickhouse.github.io/ClickStack-helm-charts
  - name: clickstack
    version: "2.1.1"
    repository: https://clickhouse.github.io/ClickStack-helm-charts