clickstack:
  clickhouse:
    enabled: false

  otel-collector:
    enabled: false

  hyperdx:
    frontendUrl: "https://hyperdx.owoicho.org"
    
    deployment:
      replicas: 1
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 1Gi

    useExistingSecret: true
    existingSecret: "clickstack-secrets"
 
    useExistingConfigSecret: true
    existingConfigSecret: "clickstack-extra-config"
    existingConfigConnectionsKey: "connections.json"
 
    ingress:
      enabled: true
      host: "hyperdx.owoicho.org"
      ingressClassName: traefik
      path: /
      pathType: Prefix
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web