apiVersion: clickhouse.com/v1alpha1
kind: KeeperCluster
metadata:
  name: clickhouse-keeper
  namespace: clickhouse
spec:
  replicas: 1
  dataVolumeClaimSpec:
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 15Gi
  containerTemplate:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  settings:
    tls:
      enabled: true
      required: true
      serverCertSecret:
        name: clickhouse-keeper-tls