apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: clickhouse
    app.kubernetes.io/name: clickhouse
  ports:
    - name: https
      port: 8443
      targetPort: 8443
    - name: native-secure
      port: 9440
      targetPort: 9440